default: &default
  adapter: postgresql
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("ABDB_DB_USER") { 'root' } %>
  password: <%= ENV.fetch("ABDB_DB_PASS") { 'password' } %>
  host:     <%= ENV.fetch("ABDB_DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: abdb_development

test:
  <<: *default
  database: abdb_test

production:
  <<: *default
  database: abdb_production
